config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/index'
  resources :tutorings
  resources :tutors
  resources :students
  resources :parents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tutoring.rb
class Tutoring < ApplicationRecord
    belongs_to :student
    belongs_to :tutor
end

app/controllers/tutorings_controller.rb
class TutoringsController < ApplicationController
  before_action :set_tutoring, only: %i[ show edit update destroy ]

  # GET /tutorings or /tutorings.json
  def index
    @tutorings = Tutoring.all
    @students = Student.all
    @tutors = Tutor.all
  end

  # GET /tutorings/1 or /tutorings/1.json
  def show
  end

  # GET /tutorings/new
  def new
    @tutoring = Tutoring.new
  end

  # GET /tutorings/1/edit
  def edit
  end

  # POST /tutorings or /tutorings.json
  def create
    @tutoring = Tutoring.new(tutoring_params)

    respond_to do |format|
      if @tutoring.save
        format.html { redirect_to @tutoring, notice: "Tutoring was successfully created." }
        format.json { render :show, status: :created, location: @tutoring }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tutoring.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutorings/1 or /tutorings/1.json
  def update
    respond_to do |format|
      if @tutoring.update(tutoring_params)
        format.html { redirect_to @tutoring, notice: "Tutoring was successfully updated." }
        format.json { render :show, status: :ok, location: @tutoring }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tutoring.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorings/1 or /tutorings/1.json
  def destroy
    @tutoring.destroy
    respond_to do |format|
      format.html { redirect_to tutorings_url, notice: "Tutoring was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutoring
      @tutoring = Tutoring.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tutoring_params
      params.require(:tutoring).permit(:date, :start, :end)
    end
end

app/helpers/tutorings_helper.rb
module TutoringsHelper
end

app/views/tutorings/_form.html.erb
<%= form_with(model: tutoring) do |form| %>
  <% if tutoring.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tutoring.errors.count, "error") %> prohibited this tutoring from being saved:</h2>

      <ul>
        <% tutoring.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.time_select :start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.time_select :end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tutorings/edit.html.erb
<h1>Editing Tutoring</h1>

<%= render 'form', tutoring: @tutoring %>

<%= link_to 'Show', @tutoring %> |
<%= link_to 'Back', tutorings_path %>

app/views/tutorings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tutorings</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Tutor</th>
      <th>Date</th>
      <th>Start</th>
      <th>End</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutorings.each do |tutoring| %>
      <tr>
        <td><%= @students.find(tutoring.student_id).name%></td>
        <td><%= @tutors.find(tutoring.tutor_id).name%></td>
        <td><%= tutoring.date %></td>
        <td><%= tutoring.start.strftime("%I:%M %p") %></td>
        <td><%= tutoring.end.strftime("%I:%M %p") %></td>
        <td><%= link_to 'Show', tutoring %></td>
        <td><%= link_to 'Edit', edit_tutoring_path(tutoring) %></td>
        <td><%= link_to 'Destroy', tutoring, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tutoring', new_tutoring_path %>

app/views/tutorings/new.html.erb
<h1>New Tutoring</h1>

<%= render 'form', tutoring: @tutoring %>

<%= link_to 'Back', tutorings_path %>

app/views/tutorings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student_Id:</strong>
  <%= @tutoring.student_id %>
</p>

<p>
  <strong>Tutor_Id:</strong>
  <%= @tutoring.tutor_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @tutoring.date %>
</p>

<p>
  <strong>Start:</strong>
  <%= @tutoring.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @tutoring.end %>
</p>

<%= link_to 'Edit', edit_tutoring_path(@tutoring) %> |
<%= link_to 'Back', tutorings_path %>