config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/index'
  resources :tutorings
  resources :tutors
  resources :students
  resources :parents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :parent
  has_many :tutorings  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
    if params[:year]
      @message = "alumno id = #{params[:id]} anio = #{params[:year]}"
      @students = Student.where("year = ?", params[:year])
    end   
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    @parents = Parent.all
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :college, :year, :email, :mobile, :parent_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :college %>
    <%= form.text_field :college %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile %>
  </div>

  <div class="field">
    <p style="font-size: 2.2em">
      Aquí debo colocar una lista para seleccionar el parent.
    </p>
    <p>Primero coloquemos una lista con los parents.</p>
     <select id="selector">
      <% @parents.each do |parent| %>
       <option><%= parent.name %></option>
      <% end %>
     </select>    

    <%= form.label :parent_id %>
    <%= form.text_field :parent_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>
<p style="font-size: 3em;">
	Hola es aquí
</p>
<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>College</th>
      <th>Year</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Parents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.college %></td>
        <td><%= student.year %></td>
        <td><%= student.email %></td>
        <td><%= student.mobile %></td>
        <td><%= student.parent_id %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<%if @message %>
 <strong>Mensaje:</strong>
  <%= @message%>
<%end%>
</p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>College:</strong>
  <%= @student.college %>
</p>

<p>
  <strong>Year:</strong>
  <%= @student.year %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @student.mobile %>
</p>

<p>
  <strong>Parents:</strong>
  <%= @student.parent_id %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>