config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/index'
  resources :tutorings
  resources :tutors
  resources :students
  resources :parents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tutor.rb
class Tutor < ApplicationRecord
    has_many :tutorings
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :set_tutor, only: %i[ show edit update destroy ]

  # GET /tutors or /tutors.json
  def index
    @tutors = Tutor.all
  end

  # GET /tutors/1 or /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @tutor = Tutor.new
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors or /tutors.json
  def create
    @tutor = Tutor.new(tutor_params)

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: "Tutor was successfully created." }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1 or /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to @tutor, notice: "Tutor was successfully updated." }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1 or /tutors/1.json
  def destroy
    @tutor.destroy
    respond_to do |format|
      format.html { redirect_to tutors_url, notice: "Tutor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tutor_params
      params.require(:tutor).permit(:name, :subject)
    end
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/tutors/_form.html.erb
<%= form_with(model: tutor) do |form| %>
  <% if tutor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tutor.errors.count, "error") %> prohibited this tutor from being saved:</h2>

      <ul>
        <% tutor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tutors/edit.html.erb
<h1>Editing Tutor</h1>

<%= render 'form', tutor: @tutor %>

<%= link_to 'Show', @tutor %> |
<%= link_to 'Back', tutors_path %>

app/views/tutors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tutors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutors.each do |tutor| %>
      <tr>
        <td><%= tutor.name %></td>
        <td><%= tutor.subject %></td>
        <td><%= link_to 'Show', tutor %></td>
        <td><%= link_to 'Edit', edit_tutor_path(tutor) %></td>
        <td><%= link_to 'Destroy', tutor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tutor', new_tutor_path %>

app/views/tutors/new.html.erb
<h1>New Tutor</h1>

<%= render 'form', tutor: @tutor %>

<%= link_to 'Back', tutors_path %>

app/views/tutors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tutor.name %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @tutor.subject %>
</p>

<%= link_to 'Edit', edit_tutor_path(@tutor) %> |
<%= link_to 'Back', tutors_path %>