config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/index'
  resources :tutorings
  resources :tutors
  resources :students
  resources :parents
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/parent.rb
class Parent < ApplicationRecord
	has_many :students
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: %i[ show edit update destroy ]

  # GET /parents or /parents.json
  def index
    @parents = Parent.all
  end

  # GET /parents/1 or /parents/1.json
  def show
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents or /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: "Parent was successfully created." }
        format.json { render :show, status: :created, location: @parent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1 or /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: "Parent was successfully updated." }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1 or /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url, notice: "Parent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parent_params
      params.require(:parent).permit(:name, :email, :mobile)
    end
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/parents/_form.html.erb
<%= form_with(model: parent) do |form| %>
  <% if parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
        <% parent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form', parent: @parent %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.name %></td>
        <td><%= parent.email %></td>
        <td><%= parent.mobile %></td>
        <td><%= link_to 'Show', parent %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent', new_parent_url %>

app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render 'form', parent: @parent %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parent.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @parent.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @parent.mobile %>
</p>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>